#image: androidsdk/android-30
image: alvrme/alpine-android:latest-jdk17

pipelines:
  branches:
    master:
      - step:
          name: Android Debug Application
          caches:
            - gradle
          script:
            - ./gradlew assembleDebug
          artifacts:
            - app/build/outputs/**